USE mt_optics;

ALTER TABLE customers
  ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS road_address VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS jibun_address VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS detail_address VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS address_type VARCHAR(20) NULL;

ALTER TABLE customer_sites
  ADD COLUMN IF NOT EXISTS postal_code VARCHAR(20) NULL,
  ADD COLUMN IF NOT EXISTS road_address VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS jibun_address VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS detail_address VARCHAR(255) NULL,
  ADD COLUMN IF NOT EXISTS address_type VARCHAR(20) NULL;

ALTER TABLE sales_orders
  ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL;

ALTER TABLE payments
  ADD COLUMN IF NOT EXISTS updated_by BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS status VARCHAR(30) NOT NULL DEFAULT 'active',
  ADD COLUMN IF NOT EXISTS deleted_at DATETIME NULL,
  ADD COLUMN IF NOT EXISTS deleted_by BIGINT UNSIGNED NULL,
  ADD COLUMN IF NOT EXISTS delete_reason VARCHAR(500) NULL;

ALTER TABLE audit_logs
  ADD COLUMN IF NOT EXISTS change_reason VARCHAR(500) NULL;

INSERT IGNORE INTO schema_migrations(version)
VALUES ('2026-07-24-v1.5-security-mobile-address-audit');
